### ISSUE TITLE
generation on meshlab

### ISSUE THREAD

**Issue by jiyoonshincml** [jianglongye/gifs#5]
Hi, i generated my 256 resolution voxels on meshlab -- and they are not displayed as a mesh but as voxels.

It happens to be the same with the demo model, how can I fix this?

**Comment by jianglongye** [comment]
Sorry for the late reply, I didn't clearly get that "they are displayed as voxels". And I have tested the demo before release, it should be a mesh. Can you kindly share some screenshots for the voxel?

**Comment by jiyoonshincml** [comment]
![image](https://user-images.githubusercontent.com/54308238/200102395-0971073f-3c95-4fab-8e3c-2b7da96b52f2.png)
Hi, thank you for your response.

Somehow my generated image looks like the screenshot above.. and I did try back face -> double, but seemed similar.

Should I change some values in generate.py or something else? thank you.

**Comment by jianglongye** [comment]
Yeah, it looks like some faces with inconsistent normals are shown in dark. But if you use back face -> double in meshlab, the result should look like the figure below. Can you send me the mesh file so that I can try to visualize it in my meshlab?

<img width="1549" alt="Screen Shot 2022-11-04 at 22 20 52" src="https://user-images.githubusercontent.com/34152111/200102579-19f5a5eb-2afd-4a42-b4b7-f7c77e67396d.png">
